![](pontificia_universidad_javeriana_logo.jpg)

<h1>Procesamiento de Datos a Gran Escala</h1>

<h2>Cuaderno 02 - Tuplas en Python</h2>

---
**Pontificia Universidad Javeriana**

**Facultad de Ingeniería**

**Materia:** Procesamiento de Datos a Gran Escala

**Número de Clase:** 1055 

**Profesor**: John Jairo Corredor Franco

**Autora:** Monica Maria Castro Benitez

**Código:** 00020574755

**Fecha:** 14-08-2026

---

## **Introducción**

<p><strong>¡Bienvenido!</strong> En este cuaderno aprenderás sobre las tuplas en el Lenguaje de Programación Python. Al final de este laboratorio, conocerás lo básico sobre las operaciones con tuplas en Python, esto incluye la indexación, el slicing y la clasificación de las tuplas.</p>

En este cuaderno se trabaja con las tuplas en Python, un tipo de dato que permite almacenar una colección ordenada e inmutable de elementos. Se abordan operaciones como la indexación positiva y negativa, la concatenación, el slicing, el ordenamiento y el anidamiento de tuplas.


## Objetivo General

Comprender y aplicar las operaciones fundamentales con tuplas en Python para el almacenamiento y manipulación de datos ordenados e inmutables.

## Objetivos Específicos

- Aplicar indexación positiva y negativa, así como slicing, para acceder a los elementos de una tupla.
- Concatenar tuplas y ordenar sus elementos utilizando la función `sorted()`.
- Acceder a elementos dentro de tuplas anidadas mediante múltiples niveles de indexación.

## Resumen de Conceptos Clave

**Tupla:** Colección ordenada e inmutable de elementos, que puede almacenar distintos tipos de datos (cadenas, enteros, decimales, e incluso otras tuplas).

**Indexación:** Permite acceder a un elemento específico de la tupla mediante su posición (positiva desde el inicio, negativa desde el final).

**Concatenación:** Se realiza con el operador `+`, y permite combinar dos o más tuplas en una nueva.

**Slicing:** Permite extraer un subconjunto de elementos de la tupla a partir de un rango de índices.

**Ordenamiento:** La función `sorted()` devuelve una nueva lista con los elementos de la tupla ordenados, sin modificar la tupla original (ya que es inmutable).

**Anidamiento:** Una tupla puede contener otras tuplas, a las que se accede usando índices sucesivos, por ejemplo `NestedT[2][1][0]`.

<h2>Tabla de Contenido</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>
            <a href="#dataset">Acerca de los conjuntos de datos (Dataset)</a>
        </li>
        <li>
            <a href="#tuple">Tuplas</a>
            <ul>
                <li><a href="index">Indexación</a></li>
                <li><a href="slice">Slicing (Sublistas)</a></li>
                <li><a href="sort">Ordenamiento</a></li>
            </ul>
        </li>
        <li>
            <a href="#escape">Exámen sobre Tuplas</a>
        </li>
    </ul>
    <p>
        Tiempo Estimado: <strong>15 min</strong>
    </p>
</div>

<hr>

<h2 id="dataset">Acerca de los conjuntos de datos (Dataset)</h2>

Imagina que obtienes de tus amigos algunas recomendaciones sobre discos de música y las compilas en una tabla con información específica de cada disco.

La tabla tiene una fila para cada disco y algunas columnas:

- **artist** - Nombre del artista
- **album** - Nombre del disco
- **released_year** - Año de estreno
- **length_min_sec** - Duración del disco (horas, minutos,segundos)
- **genre** - Género del disco
- **music_recording_sales_millions** - Ventas registradas (en millones de USD) on [SONG://DATABASE](https://cocl.us/hZvV8)
- **claimed_sales_millions** - Ventas reportadas (en millones de USD) on [SONG://DATABASE](https://cocl.us/hZvV8)
- **date_released** - Fecha del estreno
- **soundtrack** - Indica si el disco pertenece a la banda sonora de alguna película (Y) o (N)
- **rating_of_friends** - Indica la calificación de tus amigos del 1 al 10
<br>
<br>

El conjunto de datos se muestra a continuación:

<font size="1">
<table font-size:xx-small style="width:100%">
  <tr>
    <th>Artist</th>
    <th>Album</th> 
    <th>Released</th>
    <th>Length</th>
    <th>Genre</th> 
    <th>Music recording sales (millions)</th>
    <th>Claimed sales (millions)</th>
    <th>Released</th>
    <th>Soundtrack</th>
    <th>Rating (friends)</th>
  </tr>
  <tr>
    <td>Michael Jackson</td>
    <td>Thriller</td> 
    <td>1982</td>
    <td>00:42:19</td>
    <td>Pop, rock, R&B</td>
    <td>46</td>
    <td>65</td>
    <td>30-Nov-82</td>
    <td></td>
    <td>10.0</td>
  </tr>
  <tr>
    <td>AC/DC</td>
    <td>Back in Black</td> 
    <td>1980</td>
    <td>00:42:11</td>
    <td>Hard rock</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td></td>
    <td>8.5</td>
  </tr>
    <tr>
    <td>Pink Floyd</td>
    <td>The Dark Side of the Moon</td> 
    <td>1973</td>
    <td>00:42:49</td>
    <td>Progressive rock</td>
    <td>24.2</td>
    <td>45</td>
    <td>01-Mar-73</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Whitney Houston</td>
    <td>The Bodyguard</td> 
    <td>1992</td>
    <td>00:57:44</td>
    <td>Soundtrack/R&B, soul, pop</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td>Y</td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Meat Loaf</td>
    <td>Bat Out of Hell</td> 
    <td>1977</td>
    <td>00:46:33</td>
    <td>Hard rock, progressive rock</td>
    <td>20.6</td>
    <td>43</td>
    <td>21-Oct-77</td>
    <td></td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Eagles</td>
    <td>Their Greatest Hits (1971-1975)</td> 
    <td>1976</td>
    <td>00:43:08</td>
    <td>Rock, soft rock, folk rock</td>
    <td>32.2</td>
    <td>42</td>
    <td>17-Feb-76</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Bee Gees</td>
    <td>Saturday Night Fever</td> 
    <td>1977</td>
    <td>1:15:54</td>
    <td>Disco</td>
    <td>20.6</td>
    <td>40</td>
    <td>15-Nov-77</td>
    <td>Y</td>
    <td>9.0</td>
  </tr>
    <tr>
    <td>Fleetwood Mac</td>
    <td>Rumours</td> 
    <td>1977</td>
    <td>00:40:01</td>
    <td>Soft rock</td>
    <td>27.9</td>
    <td>40</td>
    <td>04-Feb-77</td>
    <td></td>
    <td>9.5</td>
  </tr>
</table></font>

<h2 id="tuple">Tuplas</h2>

En Python existen diferentes tipos de datos: cadenas, números enteros o decimales (float), etc. Todos estos tipos de datos pueden ser almacenados en una tupla como se indica a continuación:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesType.png" width="750" align="center" />

Vamos a crear tu primera tupla compuesta de: una cadena, un entero y un número decimal.

In [1]:
# Crear tu primera tupla

tuple1=(1,2,3)
tuple1

pelicula1 = ("El Padrino", 1972, 175, "Drama", 245)
pelicula1

('El Padrino', 1972, 175, 'Drama', 245)

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">Se crean dos tuplas usando paréntesis: <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple1=(1,2,3)</code>, con tres números enteros, y <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula1 = (&quot;El Padrino&quot;, 1972, 175, &quot;Drama&quot;, 245)</code>, que combina texto, enteros y datos numéricos en una sola colección ordenada.</p><p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">Como no se usa <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">print()</code>, Jupyter solo muestra el resultado de la última línea de la celda; por eso solo se ve el contenido de <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula1</code>.</p>
</div>

El tipo de dato almacenado en la variable es **tuple**.

In [0]:
# Imprime el tipo de dato de la tupla

type(tuple1)

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">type(tuple1)</code> devuelve el tipo de dato de la variable, que en este caso es <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple</code>, confirmando que se trata de una tupla.</p>
</div>

<h3 id="index">Indexación</h3>

Cada elemento dentro de la tupla puede ser accedido a través de su número de índice. La siguiente tabla representa la relación entre el número de índice y los elementos dentro de la tupla. Se puede obtener cada elemento escribiendo el nombre de la tupla seguido de corchetes conteniendo el número del índice:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesIndex.gif" width="750" align="center">

Podemos imprimir cada uno de los valores de la tupla:

In [2]:
# Imprimir la variable en cada índice

print(tuple1[0])
print(tuple1[1])
print(tuple1[2])

print(pelicula1[0])

1
2
3
El Padrino


<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">Se imprime cada elemento de <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple1</code> usando su índice: <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple1[0]</code>, <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple1[1]</code> y <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple1[2]</code> devuelven, en orden, el primer, segundo y tercer elemento.</p><p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">De la misma forma, <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula1[0]</code> accede al primer elemento de esa tupla, que es la cadena "El Padrino".</p>
</div>

Podemos imprimir el **tipo** de cada uno de los valores de la tupla:

In [0]:
# Imprimir el tipo de valor de cada uno de los índices

print(type(tuple1[0]))
print(type(tuple1[1]))
print(type(tuple1[2]))

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">type(tuple1[0])</code> devuelve el tipo de dato de cada elemento individual de la tupla, no el de la tupla completa. Como los tres valores de <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple1</code> son números enteros, las tres líneas imprimen <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">&lt;class &#x27;int&#x27;&gt;</code>.</p>
</div>

También podemos usar números de índice negativos. Vamos a usar la misma tabla de arriba con su correspondiente valor negativo:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesNeg.png" width="750" align="center">

Obtenemos el ultimo elemento de la siguiente forma (en esta ocasión no usaremos la sentencia print para mostrar los valores en pantalla):

In [3]:
# Usar un valor negativo en el índice para obtener el valor del último elemento

tuple1[-1]
print(pelicula1[-1])

245


<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple1[-1]</code> usa indexación negativa para acceder al último elemento de la tupla sin necesidad de conocer su longitud.</p><p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">De igual forma, <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula1[-1]</code> obtiene el último elemento de <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula1</code>, que es el número 245.</p>
</div>

Podemos mostrar en pantalla los siguientes dos elementos de la siguiente forma:

In [9]:
# Usar un valor negativo en el índice para obtener el valor del penúltimo elemento

tuple1[-2]
pelicula1[-2]

'Drama'

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple1[-2]</code> y <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula1[-2]</code> acceden al penúltimo elemento de cada tupla, contando desde el final hacia el inicio.</p>
</div>

In [13]:
# Usar un valor negativo en el índice para obtener el valor del antepenúltimo elemento

tuple1[-3]
pelicula1[-4]

1972

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple1[-3]</code> obtiene el antepenúltimo elemento de <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple1</code>. En <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula1</code>, que tiene 5 elementos, <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula1[-4]</code> corresponde al segundo elemento (índice 1), que es el año 1972.</p>
</div>

<h3 id="concate">Concatenación de Tuplas</h3>

Podemos concatenar o combinar tuplas utilizando el signo **+**:

In [14]:
# Concatenar dos tuplas

tuple2 = tuple1 + ("hard rock", 10)
tuple2

pelicula2 = pelicula1 + ("Francis Ford Coppola",)
pelicula2

('El Padrino', 1972, 175, 'Drama', 245, 'Francis Ford Coppola')

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">El operador <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">+</code> concatena tuplas creando una nueva: <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple2 = tuple1 + (&quot;hard rock&quot;, 10)</code> agrega dos elementos al final de <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple1</code>.</p><p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">De la misma manera, <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula2 = pelicula1 + (&quot;Francis Ford Coppola&quot;,)</code> agrega un nuevo elemento a <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula1</code>. Nótese la coma después del único elemento: es necesaria para que Python interprete <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">(&quot;Francis Ford Coppola&quot;,)</code> como una tupla y no como una cadena entre paréntesis.</p>
</div>

Podemos subdividir (slice) una tupla y obtener múltiples valores como se muestra en la siguiente imagen:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesSlice.gif" width="750" align="center">

<h3 id="slice">Slicing (Sublistas)</h3>

Podemos aplicar el slice en las tuplas, obteniendo su vez nuevas tuplas con sus elementos correspondientes:

In [0]:
# Sublista(slice) desde el índice 0 al 2

tuple2[0:3]

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple2[0:3]</code> aplica slicing para extraer los elementos en las posiciones 0, 1 y 2 (sin incluir la posición 3), devolviendo una nueva tupla con esos tres valores.</p>
</div>

Podemos obtener los últimos dos elementos de una tupla:

In [15]:
# Sublista(slice) desde el índice 3 al 4

tuple2[3:5]

pelicula2[3:5]

('Drama', 245)

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">tuple2[3:5]</code> y <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula2[3:5]</code> extraen los elementos en las posiciones 3 y 4, es decir, los dos últimos elementos de cada tupla (recordando que el índice final del slice no se incluye).</p>
</div>

Podemos obtener la longitud de una tupla usando el comando length:

In [16]:
# Obtener la longitud de la tupla

len(tuple2)

len(pelicula1)

5

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">len(tuple2)</code> y <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">len(pelicula1)</code> devuelven la cantidad de elementos que contiene cada tupla, sin importar el tipo de dato de cada uno.</p>
</div>

La siguiente imagen muestra el número de elementos:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesElement.png" width="750" align="center">

<h3 id="sort">Ordenamiento</h3>

Considérese la siguiente tupla:

In [17]:
# Tupla de ejemplo

Ratings = (0, 9, 6, 5, 10, 8, 9, 6, 2)

duraciones = (175, 152, 195, 88, 136)

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">Se definen dos tuplas de ejemplo con valores numéricos: <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">Ratings</code>, con calificaciones, y <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">duraciones</code>, con la duración en minutos de varias películas. Ambas se usarán a continuación para ilustrar el ordenamiento.</p>
</div>

Podemos ordenar los valores en la tupla y guardarlos en una nueva:

In [18]:
# Ordenar la tupla

RatingsSorted = sorted(Ratings)
RatingsSorted

duraciones_ordenadas = sorted(duraciones)
duraciones_ordenadas

[88, 136, 152, 175, 195]

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">sorted(Ratings)</code> devuelve una <b>nueva lista</b> con los elementos de <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">Ratings</code> ordenados de menor a mayor. La tupla original no se modifica porque las tuplas son inmutables.</p><p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">Lo mismo ocurre con <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">duraciones_ordenadas = sorted(duraciones)</code>: se obtiene una lista con las duraciones ordenadas ascendentemente.</p>
</div>

<h3 id="nest">Tupla Anidada</h3>

Una tupla puede contener a otras tuplas, adi como otro tipo de datos complejos. Este proceso es conocido como “anidar”. Considere la siguiente tupla con algunos elementos:

In [19]:
# Crear una tupla anidada

NestedT =(1, 2, ("pop", "rock") ,(3,4),("disco",(1,2)))

catalogo = ("El Padrino", 1972, ("Drama", "Crimen"), ("Marlon Brando", "Al Pacino"))
print(catalogo[2][0])
print(catalogo[3][1])

Drama
Al Pacino


<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">Se crea una tupla anidada, <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">NestedT</code>, que contiene números, cadenas y otras tuplas dentro de sí misma.</p><p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">De igual forma, <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">catalogo</code> anida dos tuplas: una con los géneros de la película y otra con el reparto. <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">catalogo[2][0]</code> accede primero a la tupla de géneros (índice 2) y luego a su primer elemento (índice 0), obteniendo "Drama". <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">catalogo[3][1]</code> hace lo mismo con la tupla del reparto, obteniendo "Al Pacino".</p>
</div>

El valor de cada elemento en la tupla incluyendo a otras tuplas pueden ser obtenido a través de un numero de índice como se muestra en la imagen:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesNestOne.png" width="750" align="center">

In [0]:
# Imprimir el elemento de cada índice

print("Element 0 of Tuple: ", NestedT[0])
print("Element 1 of Tuple: ", NestedT[1])
print("Element 2 of Tuple: ", NestedT[2])
print("Element 3 of Tuple: ", NestedT[3])
print("Element 4 of Tuple: ", NestedT[4])

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">Se imprime cada elemento de primer nivel de <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">NestedT</code> usando su índice (0 a 4). Nótese que los elementos en las posiciones 2, 3 y 4 son a su vez tuplas completas, no valores individuales.</p>
</div>

Podemos usar un segundo índice para acceder otras tuplas como se muestra en la siguiente imagen:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesNestTwo.png" width="750" align="center">

Podemos acceder a las tuplas anidadas:

In [0]:
# Imprimir el elemento de cada índice, incluyendo los índices anidados

print("Element 2, 0 of Tuple: ",   NestedT[2][0])
print("Element 2, 1 of Tuple: ",   NestedT[2][1])
print("Element 3, 0 of Tuple: ",   NestedT[3][0])
print("Element 3, 1 of Tuple: ",   NestedT[3][1])
print("Element 4, 0 of Tuple: ",   NestedT[4][0])
print("Element 4, 1 of Tuple: ",   NestedT[4][1])

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">Se usa un segundo índice para entrar en las tuplas anidadas: por ejemplo, <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">NestedT[2][0]</code> primero accede al elemento 2 de <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">NestedT</code> (la tupla <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">(&quot;pop&quot;, &quot;rock&quot;)</code>) y luego a su elemento 0 (<code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">&quot;pop&quot;</code>).</p><p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">El mismo patrón se repite para los índices 3 y 4, permitiendo llegar a los valores dentro de cada tupla anidada.</p>
</div>

Podemos acceder a las cadenas de las segundas tuplas anidadas usando un tercer número de índice:

In [0]:
# Imprimir el primer elemento en las segundas tuplas anidadas

NestedT[2][1][0]

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">NestedT[2][1][0]</code> usa un tercer índice: primero entra a la tupla en la posición 2, luego a su elemento 1 ("rock"), y como ese elemento es una cadena, el índice 0 accede a su primer carácter: "r".</p>
</div>

In [0]:
# Imprimir el segundo elemento en las segundas tuplas anidadas

NestedT[2][1][1]

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">NestedT[2][1][1]</code> sigue el mismo camino que la celda anterior, pero accede al segundo carácter ("o") de la cadena "rock".</p>
</div>

Podemos usar una estructura de árbol para visualizar el proceso. Cada índice nuevo corresponde a un nivel mas profundo del árbol:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesNestThree.gif" width="750" align="center">

De igual forma, podemos acceder a elementos anidados en niveles mas bajos dentro del árbol utilizando un cuarto índice:

In [0]:
# Imprimir el primer elemento en las segundas tuplas anidadas

NestedT[4][1][0]

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">NestedT[4][1][0]</code> entra a la tupla en la posición 4 (<code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">(&quot;disco&quot;,(1,2))</code>), luego a su elemento 1 (la tupla <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">(1,2)</code>), y de ahí toma su elemento 0, que es el número 1.</p>
</div>

In [0]:
# Imprimir el segundo elemento en las segundas tuplas anidadas

NestedT[4][1][1]

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">NestedT[4][1][1]</code> sigue el mismo recorrido que la celda anterior, pero accede al segundo elemento de esa tupla más interna, que es el número 2.</p>
</div>

La siguiente figura muestra la relación entre la estructura de árbol y el elemento <code>NestedT[4][1][1]</code>:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesNestFour.gif" width="750" align="center">

### Ejemplo adicional uniendo toda la teoría:
Tupla con información de una película

In [1]:
# Crear una tupla con datos de una película
pelicula1 = ("El Padrino", 1972, 175, "Drama", 245)
pelicula1

# Indexación positiva y negativa
print(pelicula1[0])
print(pelicula1[-1])

# Concatenación de tuplas
pelicula2 = pelicula1 + ("Francis Ford Coppola",)
pelicula2

# Slicing
print(pelicula2[1:4])

# Ordenar duraciones de varias películas
duraciones = (175, 152, 195, 88, 136)
duraciones_ordenadas = sorted(duraciones)
duraciones_ordenadas

# Tupla anidada
catalogo = ("El Padrino", 1972, ("Drama", "Crimen"), ("Marlon Brando", "Al Pacino"))
print(catalogo[2][0])
print(catalogo[3][1])

El Padrino
245
(1972, 175, 'Drama')
Drama
Al Pacino


<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">Este bloque reúne, en un solo ejemplo, todas las operaciones vistas en el cuaderno aplicadas a los datos de una película:</p><p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><b>Indexación</b> positiva y negativa (<code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula1[0]</code>, <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula1[-1]</code>) para acceder al primer y último elemento.</p><p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><b>Concatenación</b> (<code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula1 + (&quot;Francis Ford Coppola&quot;,)</code>) para agregar un nuevo dato a la tupla.</p><p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><b>Slicing</b> (<code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">pelicula2[1:4]</code>) para extraer un rango de elementos.</p><p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><b>Ordenamiento</b> (<code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">sorted(duraciones)</code>) para obtener una lista ordenada a partir de una tupla.</p><p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><b>Anidamiento</b> (<code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">catalogo[2][0]</code>, <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">catalogo[3][1]</code>) para acceder a valores dentro de tuplas contenidas en otra tupla.</p>
</div>

<h2 id="quiz">Exámen sobre Tuplas</h2>

Considérese la siguiente tupla:

In [20]:
# Tupla de ejemplo

genres_tuple = ("pop", "rock", "soul", "hard rock", "soft rock", \
                "R&B", "progressive rock", "disco") 
genres_tuple

('pop',
 'rock',
 'soul',
 'hard rock',
 'soft rock',
 'R&B',
 'progressive rock',
 'disco')

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">Se crea la tupla <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">genres_tuple</code> con ocho géneros musicales. La barra invertida <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">\\</code> al final de la primera línea le indica a Python que la instrucción continúa en la línea siguiente, sin que esto afecte el contenido de la tupla.</p>
</div>

Encontrar la longitud de la tupla, <code>genres_tuple</code>:

In [21]:
# Escribe abajo tu código y presiona Shift+Enter para ejecutarlo

len(genres_tuple)

8

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">len(genres_tuple)</code> devuelve la cantidad de elementos de la tupla, que en este caso es 8.</p>
</div>

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesQuiz.png" width="1100" align="center">

Haz doble clic __aquí__ para ver la solución.

<!-- Your answer is below:
len(genres_tuple)
-->

Accede al elemento en el índice 3:

In [22]:
# Escribe abajo tu código y presiona Shift+Enter para ejecutarlo

genres_tuple[3]

'hard rock'

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">genres_tuple[3]</code> accede al elemento en la posición 3 (la cuarta, contando desde 0), que corresponde a "hard rock".</p>
</div>

Haz doble clic __aquí__ para ver la solución.

<!-- Your answer is below:
genres_tuple[3]
-->

Utiliza el slicing para obtener los índices 3, 4 y 5:

In [23]:
# Escribe abajo tu código y presiona Shift+Enter para ejecutarlo

# Nota: recuerda que en el slicing, el primer índice es inclusivo y el segundo índice es exclusivo. 
# Por lo tanto, si quieres obtener los elementos en los índices 3, 4 y 5, debes escribir 3:6.
genres_tuple[3:6]

('hard rock', 'soft rock', 'R&B')

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">genres_tuple[3:6]</code> aplica slicing para obtener los elementos en las posiciones 3, 4 y 5. Como el índice final del slice es exclusivo, se debe escribir 6 para incluir hasta la posición 5.</p>
</div>

Haz doble clic __aquí__ para ver la solución.

<!-- Your answer is below:
genres_tuple[3:6]
-->

Encuentra los primeros dos elementos de la tupla <code>genres_tuple</code>:

In [24]:
# Escribe abajo tu código y presiona Shift+Enter para ejecutarlo
genres_tuple[0:2]

('pop', 'rock')

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">genres_tuple[0:2]</code> extrae los dos primeros elementos de la tupla (posiciones 0 y 1), devolviendo <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">(&#x27;pop&#x27;, &#x27;rock&#x27;)</code>.</p>
</div>

Haz doble clic __aquí__ para ver la solución.

<!-- Your answer is below:
genres_tuple[0:2]
-->

Encuentra el primer índice de <code>"disco"</code>:

In [27]:
# Escribe abajo tu código y presiona Shift+Enter para ejecutarlo
genres_tuple.index("disco")

7

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;"><code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">genres_tuple.index(&quot;disco&quot;)</code> busca el valor "disco" dentro de la tupla y devuelve el índice de su primera aparición, que es 7.</p>
</div>

Haz doble clic __aquí__ para ver la solución.

<!-- Your answer is below:
genres_tuple.index("disco")
-->

Genera una lista ordenada desde la tupla <code>C_tuple=(-5, 1, -3)</code>:

In [26]:
# Escribe abajo tu código y presiona Shift+Enter para ejecutarlo
C_tuple=(-5, 1, -3)

C_tupleSorted = sorted(C_tuple)
C_tupleSorted

[-5, -3, 1]

<div style="background:#f7f7f8; border-left:4px solid #7a7a7a; border-radius:4px; padding:12px 18px; font-family:Arial,sans-serif;">
<p style="margin:0 0 8px 0; font-size:13.5px; font-weight:700; color:#2c2c2c;">Explicación del bloque</p>
<p style="margin:6px 0; font-size:14px; line-height:1.55; color:#2c2c2c;">Se define la tupla <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">C_tuple=(-5, 1, -3)</code> con números negativos y positivos. <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">sorted(C_tuple)</code> devuelve una lista nueva con esos valores ordenados de menor a mayor: <code style="background:#eef0f2; color:#333; padding:1px 6px; border-radius:4px; font-size:13px;">[-5, -3, 1]</code>.</p>
</div>

Haz doble clic __aquí__ para ver la solución.

<!-- Your answer is below:
C_tuple = (-5, 1, -3)
C_list = sorted(C_tuple)
C_list
-->

## Conclusiones

Las tuplas son útiles cuando se necesita que los datos no cambien durante la ejecución del programa, en comparación de las listas, que sí permiten modificaciones. Por otro lado, la indexación negativa facilita el acceso a los últimos elementos sin necesidad de conocer la longitud exacta de la tupla, lo que simplifica el manejo de datos de tamaño variable. Finalmente, el anidamiento permite representar estructuras de datos más complejas, aunque requiere tener claro cuántos niveles de índices hay que recorrer para llegar al valor deseado.